# Generated by Django 3.0.5 on 2020-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test descriptio fsakdhfkajfh ahsfkajhfjkd hdjfhkjhdf kdfjnkshjdfkhjsjdf hsfjhshfdfjih'),
            preserve_default=False,
        ),
    ]
