# Generated by Django 3.0.5 on 2020-04-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200405_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
    ]
